language: python
python:
  - "3.5"

# command to install dependencies
install:
- pip install coverage python-coveralls 'grammpy==1.2.1' 'grammpy-transforms==1.2.5'

# command to run tests with coverage
script:
- coverage run --source=pyparsers -m unittest discover -s tests -p "*Test.py" -q

# report coverage
after_script:
- coverage report -m
- coveralls

# disable email notifications
notifications:
  email: false
